### 1.测试登录
POST http://localhost:51801/api/v1/login/login_auth
Content-Type: application/json

{
  "phone": "13511223455",
  "password": "12"
}

<> 2023-12-26T212323.200.json
<> 2023-12-26T212306.200.json

### 2.网关测试登录
POST http://localhost:51601/user/api/v1/login/login_auth
Content-Type: application/json

{
  "phone": "13511223455",
  "password": "wangwu"
}

### 3.测试freemarker
http://localhost:8881/basic

### 4.freemarker-list测试
http://localhost:8881/list